name: Container-Security-Scans

on:
  pull_request:
    branches:
      - master
      
  # enable manual dispatch from 'Actions'-Tab
  workflow_dispatch: null

jobs:
  container_scan_docker_image:
    name: container_scan_docker_image
    runs-on: [btf-runner]
    steps:
      - name: Setup Vars
        id: setup
        run: |
          echo "IMAGE_NAME=nginx:latest_css" >> $GITHUB_ENV
          echo "Image Name from env"
          echo ${{ env.IMAGE_NAME }}
          echo ::set-output name=IMAGE_NAME::"nginx:latest_css"
          echo "Image Name from steps"
          echo ${{ steps.vars.outputs.IMAGE_NAME }}

      - uses: actions/checkout@v2

      - name: Build image on local machine
        id: build_image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Scan image
        id: scan_image
        uses: sip-workflow-templates/container-security-scan@master
        with:
          http_proxy: http://security-proxy.emea.svc.corpintra.net:3128
          pcc_console_url: https://consec-scan.app.corpintra.net/
          pcc_user: ${{ secrets.CSS_USER }}
          pcc_pass: ${{ secrets.CSS_PWD }}
          image_name: ${{ env.IMAGE_NAME }}

      - name: Process scan results
        id: set_var
        run: |
          summary=$(cat pcc_scan_results.json | jq '.results[0] | {vulnerabilityScanPassed: .vulnerabilityScanPassed, vulnerabilityDistribution: .vulnerabilityDistribution, complianceScanPassed: .complianceScanPassed, complianceDistribution: .complianceDistribution}')
          vulnerabilities=$(cat pcc_scan_results.json | jq -c -r '"ID\tCVSS\tSeverity\tLink","--------------\t----\t--------\t----------------------------------------------------------", (.results[0].vulnerabilities[] | [.id, .cvss // "?.?", .severity, .link] | @tsv)' | column -t -s $'\t')
          compliances=$(cat pcc_scan_results.json | jq -c -r '"Title\tSeverity", "----------------------------------------------------------------------\t--------", (.results[0].compliances[] | [.title, .severity] | @tsv)' | column -t -s $'\t')
          echo "::set-output name=scan_result_summary::$summary"
          echo "::set-output name=scan_result_vulnerabilities::$vulnerabilities"
          echo "::set-output name=scan_result_compliances::$compliances"

      - name: test
        run: |
          echo "=================================="
          echo ${{ steps.set_var.outputs.scan_result_summary }}
          echo "=================================="
          echo ${{steps.set_var.outputs.scan_result_vulnerabilities}}
          echo "=================================="
          echo ${{steps.set_var.outputs.scan_result_compliances}}
      
      - uses: actions/upload-artifact@v2
        with:
          name: pcc-scan-results
          path: ${{ github.workspace }}/pcc_scan_results.json

      - name: Comment results on pull_request
        id: comment_results_on_pr
        uses: sip-workflow-templates/github-script@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: JSON.stringify({summary: ${{steps.set_var.outputs.scan_result_summary}}, vulnerabilities: ${{steps.set_var.outputs.scan_result_vulnerabilities}}, compliances: ${{steps.set_var.outputs.scan_result_compliances}} })
            })

      - name: Clean image built on local machine
        id: clean_image
        run: docker rmi ${{ env.IMAGE_NAME }}
